apiVersion: v1
kind: Service
metadata:
  name: express-backend-service
spec:
  selector:
    app: express-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000 # Port you will use to access the service
      targetPort: 5000 # Port the container is listening on (must match Dockerfile)
